export const feedback = {
  Analytic: "/images/feedback/Analytic.svg",
  Analytics: "/images/feedback/Analytics.svg",
  "Bad gateway": "/images/feedback/Bad gateway.svg",
  Banking: "/images/feedback/Banking.svg",
  "Bear market": "/images/feedback/Bear market.svg",
  "Build a community": "/images/feedback/Build a community.svg",
  "Complete task": "/images/feedback/Complete task.svg",
  "Credit card payment": "/images/feedback/Credit card payment.svg",
  "Crypto investment": "/images/feedback/Crypto investment.svg",
  "Customer support feedback": "/images/feedback/Customer support feedback.svg",
  "Data report": "/images/feedback/Data report.svg",
  Debt: "/images/feedback/Debt.svg",
  "Empty folder": "/images/feedback/Empty folder.svg",
  "Empty inbox": "/images/feedback/Empty inbox.svg",
  "Error 404": "/images/feedback/Error 404.svg",
  Find: "/images/feedback/Find.svg",
  Form: "/images/feedback/Form.svg",
  "International payment": "/images/feedback/International payment.svg",
  "Investment in stocks": "/images/feedback/Investment in stocks.svg",
  "Investment portfolio": "/images/feedback/Investment portfolio.svg",
  Investments: "/images/feedback/Investments.svg",
  "Maths teacher": "/images/feedback/Maths teacher.svg",
  "Mobile payment": "/images/feedback/Mobile payment.svg",
  "No event": "/images/feedback/No event.svg",
  "No orders": "/images/feedback/No orders.svg",
  "No results found": "/images/feedback/No results found.svg",
  "Nothing here": "/images/feedback/Nothing here.svg",
  "Online banking": "/images/feedback/Online banking.svg",
  "Online money transfer": "/images/feedback/Online money transfer.svg",
  "Page not found": "/images/feedback/Page not found.svg",
  "Save money": "/images/feedback/Save money.svg",
  "Save time (1)": "/images/feedback/Save time (1).svg",
  "Save time": "/images/feedback/Save time.svg",
  "Saving money": "/images/feedback/Saving money.svg",
  Searching: "/images/feedback/Searching.svg",
  "Success (1)": "/images/feedback/Success (1).svg",
  Success: "/images/feedback/Success.svg",
  "Upload photos": "/images/feedback/Upload photos.svg",
  "Visual data": "/images/feedback/Visual data.svg",
  Welcome: "/images/feedback/Welcome.svg",
};
